import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";


export const metadata: Metadata = {
  title: "WTG",
  description: "Generated by create next app",
  icons: {
		icon: "/wtg-favicon-color.ico",
	},
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
     <body>
       <AntdRegistry>{children}</AntdRegistry>
     </body>
   </html>
  );
}
